package com.example.cleanrecovery.ytdlp;

import android.content.Context;
import android.util.Log;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * 持久化 Cookie 容器（对应 yt-dlp {@code YoutubeDLCookieJar} + Netscape 格式）。
 *
 * <p>对应计划 D1 / D3 / D4：解决 WebView Cookie 不共享、cookie 持久化缺失问题。</p>
 *
 * <h3>核心场景</h3>
 * <ul>
 *   <li><b>D1 WebView Cookie 同步</b>：从 {@code WebView.CookieManager} 与
 *       {@code document.cookie} 同步到本 jar，下载 googlevideo 直链时注入</li>
 *   <li><b>D3 cookie 持久化</b>：以 Netscape {@code cookies.txt} 格式存到磁盘</li>
 *   <li><b>D4 登录态</b>：用户在 BrowserActivity 登录站点后，cookie 自动写入本 jar</li>
 * </ul>
 *
 * <p>线程安全：内部用 {@link CopyOnWriteArrayList}，读多写少场景安全。</p>
 */
public final class PersistentCookieJar implements CookieJar {

    private static final String TAG = "CookieJar";
    private static final String COOKIES_FILE = "cookies.txt";
    private static final String NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n# Generated by CleanRecovery yt-dlp port\n";

    private static volatile PersistentCookieJar instance;

    private final CopyOnWriteArrayList<Cookie> cookies = new CopyOnWriteArrayList<>();
    private final File storeFile;

    private PersistentCookieJar(File storeFile) {
        this.storeFile = storeFile;
        loadFromDisk();
    }

    /** 获取单例（懒加载，首次调用需 Context）。 */
    public static PersistentCookieJar getInstance(Context context) {
        if (instance == null) {
            synchronized (PersistentCookieJar.class) {
                if (instance == null) {
                    File f = new File(context.getApplicationContext().getFilesDir(), COOKIES_FILE);
                    instance = new PersistentCookieJar(f);
                }
            }
        }
        return instance;
    }

    /** 测试用：直接构造（不持久化）。 */
    public static PersistentCookieJar forTesting() {
        return new PersistentCookieJar(null);
    }

    @Override
    public String cookieHeaderFor(String requestUrl) {
        List<Cookie> matched = cookiesFor(requestUrl);
        if (matched.isEmpty()) return "";
        StringBuilder sb = new StringBuilder();
        for (Cookie c : matched) {
            if (sb.length() > 0) sb.append("; ");
            sb.append(c.name).append('=').append(c.value);
        }
        return sb.toString();
    }

    @Override
    public List<Cookie> cookiesFor(String requestUrl) {
        String host = extractHost(requestUrl);
        boolean isSecure = requestUrl != null && requestUrl.startsWith("https://");
        String path = extractPath(requestUrl);

        List<Cookie> matched = new ArrayList<>();
        for (Cookie c : cookies) {
            if (!c.matches(host)) continue;
            if (c.secure && !isSecure) continue;
            if (c.path != null && path != null && !path.startsWith(c.path)) continue;
            matched.add(c);
        }
        return matched;
    }

    @Override
    public void putCookie(Cookie cookie) {
        if (cookie == null || cookie.name == null || cookie.domain == null) return;
        // 覆盖同名同域同路径
        List<Cookie> toRemove = new ArrayList<>();
        for (Cookie existing : cookies) {
            if (sameIdentity(existing, cookie)) toRemove.add(existing);
        }
        cookies.removeAll(toRemove);
        cookies.addIfAbsent(cookie);
        saveToDisk();
    }

    @Override
    public void putCookies(List<Cookie> list) {
        if (list == null || list.isEmpty()) return;
        for (Cookie c : list) {
            if (c == null || c.name == null || c.domain == null) continue;
            List<Cookie> toRemove = new ArrayList<>();
            for (Cookie existing : cookies) {
                if (sameIdentity(existing, c)) toRemove.add(existing);
            }
            cookies.removeAll(toRemove);
            cookies.addIfAbsent(c);
        }
        saveToDisk();
    }

    @Override
    public void clear() {
        cookies.clear();
        saveToDisk();
    }

    @Override
    public boolean isEmpty() {
        return cookies.isEmpty();
    }

    /** 当前所有 cookie（不可变快照，用于调试与同步）。 */
    public List<Cookie> snapshot() {
        return new ArrayList<>(cookies);
    }

    /** 提取 URL 的 host（小写）。 */
    static String extractHost(String url) {
        if (url == null) return null;
        try {
            return new URL(url).getHost().toLowerCase();
        } catch (Exception e) {
            // 兜底：scheme://host/path
            int schemeEnd = url.indexOf("://");
            if (schemeEnd <= 0) return null;
            int pathStart = url.indexOf('/', schemeEnd + 3);
            String host = pathStart > 0
                    ? url.substring(schemeEnd + 3, pathStart)
                    : url.substring(schemeEnd + 3);
            // 去端口
            int colon = host.indexOf(':');
            if (colon > 0) host = host.substring(0, colon);
            return host.toLowerCase();
        }
    }

    /** 提取 URL 的 path。 */
    static String extractPath(String url) {
        if (url == null) return null;
        try {
            String p = new URL(url).getPath();
            return (p == null || p.isEmpty()) ? "/" : p;
        } catch (Exception e) {
            return "/";
        }
    }

    private boolean sameIdentity(Cookie a, Cookie b) {
        return a.name.equals(b.name)
                && (a.domain == null ? b.domain == null : a.domain.equalsIgnoreCase(b.domain))
                && (a.path == null ? b.path == null : a.path.equals(b.path));
    }

    // ===== Netscape 格式持久化 =====

    private void loadFromDisk() {
        if (storeFile == null || !storeFile.exists()) return;
        try (BufferedReader br = new BufferedReader(
                new InputStreamReader(new FileInputStream(storeFile), StandardCharsets.UTF_8))) {
            String line;
            int loaded = 0;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;
                // Netscape 格式：domain\tflag\tpath\tsecure\texpiration\tname\tvalue
                String[] parts = line.split("\t");
                if (parts.length < 7) continue;
                try {
                    String domain = parts[0];
                    String path = parts[2];
                    boolean secure = "TRUE".equalsIgnoreCase(parts[3]);
                    String name = parts[5];
                    String value = parts[6];
                    cookies.addIfAbsent(new Cookie(name, value, domain, path, secure, false));
                    loaded++;
                } catch (Exception ignore) {}
            }
            Log.i(TAG, "loaded " + loaded + " cookies from " + storeFile.getName());
        } catch (Exception e) {
            Log.w(TAG, "load cookies failed: " + e.getMessage());
        }
    }

    private synchronized void saveToDisk() {
        if (storeFile == null) return;
        try (OutputStreamWriter w = new OutputStreamWriter(
                new FileOutputStream(storeFile), StandardCharsets.UTF_8)) {
            w.write(NETSCAPE_HEADER);
            for (Cookie c : cookies) {
                // domain  flag  path  secure  expiration(0=永久)  name  value
                String domain = c.domain != null ? c.domain : "";
                String flag = domain.startsWith(".") ? "TRUE" : "FALSE";
                String path = c.path != null && !c.path.isEmpty() ? c.path : "/";
                String secure = c.secure ? "TRUE" : "FALSE";
                String name = c.name != null ? c.name : "";
                String value = c.value != null ? c.value : "";
                w.write(domain + "\t" + flag + "\t" + path + "\t" + secure + "\t0\t" + name + "\t" + value + "\n");
            }
        } catch (Exception e) {
            Log.w(TAG, "save cookies failed: " + e.getMessage());
        }
    }
}
